apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default 
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/${DOCKERHUB_USERNAME}/my-app:latest  # 🔹 Docker Hub image
        ports:
        - containerPort: 80
