# Gebruik een officiële NGINX image van Docker Hub als basis
FROM nginx:latest

# Zet een eenvoudige HTML-pagina in de webserver
COPY ./index.html /usr/share/nginx/html/index.html

# Zorg ervoor dat NGINX draait op poort 80
EXPOSE 80
