---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
    metallb.io/ip-allocated-from-pool: default-pool
  creationTimestamp: "2025-02-07T14:38:24Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.2
    helm.sh/chart: argo-cd-7.8.2
  name: argocd-server
  namespace: argocd
  resourceVersion: "216693"
  uid: 4022a647-16d4-4a5b-9df5-4c019b96b3df
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.52.130
  clusterIPs:
    - 10.43.52.130
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.178.202
  ports:
    - name: http
      nodePort: 30969
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 31862
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.178.202
        ipMode: VIP
