---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: |
      AgCLo8y1hc8Z5TixyGrJKtELHgPgEPKMcsFOaV9Mz42yYQeRGpi6CVSf8FpsRy1dAh9SSf1xmy+/MwbTFVYSGYR4facqz5A+ZUa+96ggb5Z61g+Zw5Bg4IRT/blHRiFgFES0nYwpsYQUbYaDqx6HQj34fLicbGk4NWi9YfDoBi4+ZMNQExfUS4DFdzwij/6YE15ry4DS53ndSYJzwEq6OqdLrRuJ8kawlSOV1sARsARbD0vHxl5AAKN/CHZOpmEnOFF+tBgC8tVusszx5x9+EwL8HwYS5cSdC/F2sPwv43r8GxT0i0KL6PPrcXeIi+B23varimVdvYfkoHyEowT8aiYW2NqYPR1uV5XS6MehuxlhtYFVe8+SyDtAM9MghTj0ZzX0IDBAKWU+f1ubcAYH8diPHJCgtx8oN+Ff9A2Ug5vb4ehuxa5Sz59ok2gLwoO0P/PO2dvVa0HJkKmMKX9qwV+wCE5VJ/BusUWTklylA452EsfqQmWaJV/aJId3/CvOMaO1Rr/0fBaFr6oolp/1vyTh0gpzFWK8oeDXnux66yKzzxyhByVpgiia7VzZZuM/wmztFK/6A5NVUelGFCBa2YEPg1ty9wXCteW4A6uxrq87vdWeI14gJNQsR9DyzDNFDQoip1Ak8cOWSRVgfDz8Jp8ZiTnX5JHlqcu9JaDSDN9lG6Pycj0lNPpJqdxr06K4l6kAW+QEQmfh6kftgDvZfqRcDncMm+p+MaEARTnm38NdRswG3HOAe3EdR6IGe9Iey6IyUvFV1T7NEHnH9dxQlFz6RRf34tqBk1TXt9Y=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
    type: Opaque
