---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.203
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: pihole
