---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.201
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-app
